### ISSUE TITLE
熊猫赚废了？

### ISSUE THREAD

**Issue by xinsibuhui** [Huansheng1/my-qinglong-js#1]
熊猫赚废了？账号[1] 登录失败：{"StateCode":1051,"errorMessage":null,"InnerData":null,"PropId":0,"PropType":0,"ShowDelay":0,"FinishAchieveMent":false,"FinishAchieveMentName":null,"AppendAchieveId":0}

====幻生提示：无可用账号，请检查配置============ 任务结束 ================

**Comment by Huansheng1** [comment]
已修复
