### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by mochen1027** [Huansheng1/my-qinglong-js#10]
服务器鄞响等都报错是什么原因，麻烦大佬看看
![Screenshot_20231001_085430_com huawei browser](https://github.com/Huansheng1/my-qinglong-js/assets/104153672/b08dab05-7bff-4442-afe9-cd4b5255fd83)
![Screenshot_20231001_085423_com huawei browser](https://github.com/Huansheng1/my-qinglong-js/assets/104153672/93a18797-857f-4aa5-b857-7a21f3f8e062)

**Comment by Huansheng1** [comment]
安装这个nodejs模块：
![image](https://github.com/Huansheng1/my-qinglong-js/assets/33859558/c0ce80f7-a665-444d-8d6c-6676d3bdac6a)
