### ISSUE TITLE
57box不能选择开盒类型

### ISSUE THREAD

**Issue by WinterBoring** [Huansheng1/my-qinglong-js#16]
脚本里有个开盒矿石数量，但设置准备开199的，只是满了199执行开80的盒子！请大佬能不能加一个指定开盒参数，比如开巧克力122，饮料199，泡面199类型，谢谢！

**Comment by Huansheng1** [comment]
晚上再加

**Comment by Huansheng1** [comment]
已更

**Comment by WinterBoring** [comment]
> 已更

大佬，神速！！！！能否加个通知！谢谢

**Comment by Huansheng1** [comment]
> > 已更
> 
> 大佬，神速！！！！能否加个通知！谢谢

不想加
