### ISSUE TITLE
科技工作者之家运行报错

### ISSUE THREAD

**Issue by yanstu** [Huansheng1/my-qinglong-js#24]
-------- 开始【第 1 个账号】--------

开始 任务
TypeError: Cannot read properties of undefined (reading 'token')
    at _0x5aca92 (/ql/data/scripts/self/ylw/kjgzzzj.js:16:24916)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x4ae55f (/ql/data/scripts/self/ylw/kjgzzzj.js:16:13954)
    at async /ql/data/scripts/self/ylw/kjgzzzj.js:16:10577
    检查更新成功
{
  code: 301,
  msg: '请登录',
  trace_id: 'e849f127-2378-4c7e-ab4e-68fee3f09a31'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '6d729a29-e2cb-41ca-b65d-f166a77e7905'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '7f542410-12f3-4d78-b8d3-fc636229abd0'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '1f16972e-5297-4845-9151-e25fa015c95a'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '2bfa5a71-cced-4949-981b-8751375933b1'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '6eeda67e-62d3-43c3-8527-5ff9472a8de3'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '517d5ba0-36eb-4976-a726-6d7aa0b7f63f'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '61705700-b65d-408a-b940-beadf3fa0dd7'
}
{
  code: 301,
  msg: '请登录',
  trace_id: 'ab1640e1-5b7c-40e8-9678-2f632db2c4b9'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '7cde3ea5-cac7-4510-929c-f8607d0b26a2'
}
{
  code: 301,
  msg: '请登录',
  trace_id: '54b45899-0a73-4c75-9164-42d2d401688d'
}
{
  code: 301,
  msg: '请登录',
  trace_id: 'cfbcceb7-0f71-4f9f-8196-4d556225aa34'
}
{
  code: '100120033',
  msg: '抽奖次数用光了，请明日再来',
  data: [ '抽奖次数用完，明日在来' ],
  trace_id: 'fa7f9332-afd4-4a2e-850f-003e85ea4882'
}
    分享成功
{
  code: '100120033',
  msg: '抽奖次数用光了，请明日再来',
  data: [ '抽奖次数用完，明日在来' ],
  trace_id: 'f7ff90e4-debe-4eab-90ac-99bd56cbe781'
}
{
  code: 301,
  msg: '请登录',
  trace_id: 'b72725d8-a7e6-4262-a24a-ed866fd1d486'
}

**Comment by Huansheng1** [comment]
账号密码问题，自己检查

**Comment by yanstu** [comment]
![image](https://github.com/Huansheng1/my-qinglong-js/assets/47344296/a6e2ace7-3c9e-4a74-afef-acef4f3f656c)
但是可以抽奖和分享诶

**Comment by Huansheng1** [comment]
没登录也能分享
