### ISSUE TITLE
nhsy问题

### ISSUE THREAD

**Issue by a1564471347** [Huansheng1/my-qinglong-js#6]
跑不了怎么回事
## 执行结束... 2023-09-02 16:40:45  耗时 1 秒

**Comment by Huansheng1** [comment]
一定是哪里报错了，多运行几次，直到有错误信息，青龙会吞日志

**Comment by a1564471347** [comment]
> 一定是哪里报错了，多运行几次，直到有错误信息，青龙会吞日志

日志里面就是这样，是不是变量名字错误了

**Comment by a1564471347** [comment]
> 一定是哪里报错了，多运行几次，直到有错误信息，青龙会吞日志

你自己可以跑吗

**Comment by Huansheng1** [comment]
已更新，上传错了文件

**Comment by a1564471347** [comment]
> 已更新，上传错了文件

可以了，还有硬声可以写个脚本吗

**Comment by Huansheng1** [comment]
> > 已更新，上传错了文件
> 
> 可以了，还有硬声可以写个脚本吗

萌新群主不是写了么

**Comment by a1564471347** [comment]
> > > 已更新，上传错了文件
> > 
> > 
> > 可以了，还有硬声可以写个脚本吗
> 
> 萌新群主不是写了么，除非别人写的时候我已经写过了，不然不会重新造轮子🙁

那个出问题了，而且只能签到和点赞
