### ISSUE TITLE
南湖声音报错

### ISSUE THREAD

**Issue by qq846511277** [Huansheng1/my-qinglong-js#8]
运行环境 青龙面版 v2.15.16  本地N1 

报错信息如图：
账号[1],App启动成功 😄 
账号[1],启动WebView成功 😄 
账号[1],Web初始化成功 😄 
账号[1],获取版本信息成功 😄 
账号[1],获取App配置成功 😄 
账号[1],登录成功 😄 
账号[1],登录初始化:失败 🙁 了呢,原因：处理失败【
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1
; Data truncation: Data too long for column 'platform' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1】

**Comment by Huansheng1** [comment]
已更新
